language: perl
sudo: true
before_install:
    - "sudo apt-get -yq update"
    - "apt-get -yq --force-yes --no-install-recommends --no-install-suggests install libgd-gd2-perl libsnmp-perl graphviz snmp-mibs-downloader libmojolicious-perl libmodule-install-perl libtest-most-perl"
install:
    - "cpanm -n --installdeps ."

perl:
    - "blead"
    - "dev"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
