language: perl

addons:
  apt:
    packages:
    - libsnmp-dev
    - snmp-mibs-downloader
    - graphviz
    - libgd-gd2-perl

before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.30"
    - "5.28"
    - "5.26"

matrix:
  include:
    - perl: 5.30
      env: COVERAGE=1   # enables coverage+coveralls reporting
