language: perl
sudo: false

addons:
  apt:
    packages:
    - libsnmp-dev
    - snmp-mibs-downloader
    - graphviz
    - libgd-gd2-perl

before_install:
    - curl https://gist.githubusercontent.com/rfdrake/bee49eccd96f4c3af7ab/raw/7e70a6886d3d0914f0d0586046630a728ae3df2c/copy-module-to-perlbrew | /usr/bin/perl - GD.pm libgd-gd2-perl $(perl -e 'print $INC[0]')| sh -x
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.08"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
