language: perl
sudo: true

addons:
  apt:
    packages:
    - libsnmp-dev
    - snmp-mibs-downloader
    - graphviz

before_install:
    - sudo apt-get update
    - sudo apt-get build-dep libgd-gd2-perl
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.8"
    - "5.10"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
