language: perl
sudo: true

env:
  - NETSNMP_DONT_CHECK_VERSION=1
before_install:
    - "sudo apt-get -yq update"
    - "sudo apt-get -yq install graphviz libsnmp-perl libsnmp-dev"
    - "sudo apt-get -yq build-dep libgd-gd2-perl"
    - "cpanm GD Module::Load SNMP"
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
