language: perl
perl:
    - "blead"
    - "dev"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl

before_install:
     - sudo apt-get update -qq
     - sudo apt-get install -y graphviz
     - eval $(curl https://travis-perl.github.io/init) --auto
