#!/usr/bin/perl -I/home/pwhiting/barn/shed

# Copyright (C) 2000 Peter Whiting (Sprint)
# This module is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
# This module is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.


use Fig;
use Getopt::Long;
GetOptions(\%opts,
           "csmap",
           "ssmap",
           "jpeg");
@data=<>;
$fig=new Fig(fig=>[@data],%opts);
if(defined $opts{csmap}) {
    $fig->BuildMap;
    print $fig->csImageMap;
} elsif(defined $opts{ssmap}) {
    $fig->BuildMap;
    print $fig->ssImageMap;
    
} else {
    $fig->BuildImage;
    if (defined $opts{jpeg}) {
        print $fig->jpeg();
    } else {
        print $fig->png;
    }
}






