#!/usr/bin/perl

# Copyright (C) 2000 Peter Whiting (Sprint)

# This module is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
# This module is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

use strict;
use CIBH::Config qw ( $default_options );
use CIBH::Fig;
use CGI;
use IO::File;

my $cgi = new CGI;
$cgi->import_names('param');

my $opts={ %{$default_options}, $param::opts ? %{$param::opts} : {} };
my $network=$opts->{network};
my $author=$opts->{contact};
my $dir=$opts->{'map_path'};

$network=$param::net if defined $param::net;
my $cat=(defined $param::td)?$opts->{script_path}.'/3d':'/bin/cat';

# figure out if we're using & or ? based on number of existing arguments
my $sep = ($cgi->self_url()=~/\?/)?"&":"?");

#
# End of user configurations
#

if (! -r "$dir/$param::file".".fig.used" && ! -r "$dir/$param::file".".gv.svg") {
    opendir(THISDIR,"$dir");
    my @allfiles=grep(/\.fig\.used$/ || /\.gv\.svg$/,readdir(THISDIR));
    closedir(THISDIR);

    my @files = ();
    foreach my $file (sort @allfiles) {
        warn "$file\n" if $opts->{debug};
        ($file)=($file=~/^(.*)(\.fig\.used|\.gv\.svg)/);
        my $url=$cgi->self_url().$sep."file=$file";
        push @files,"<a href=\"$url\">$file</a>\n";
    }

    my @tbl;
    while(@files) {push @tbl,$cgi->table($cgi->Tr([$cgi->td([splice(@files,0,10)])])); }
    print
        $cgi->header(-expires=>'now',refresh=>'300'),
        $cgi->start_html(-title=>'Barn Mapping',
                   -author=>$author,
                   -BGCOLOR=>'ffffff'),

        $cgi->center($cgi->h1("Available Maps"),@tbl),
        $cgi->end_html;
    exit;
} elsif ( -r "$dir/$param::file".'.gv.svg') {
    if ($param::mode eq 'svg') {
        open my $fh, '<', "$dir/$param::file".'.gv.svg' || die;
        read $fh, my $buffer, -s $fh or die "Couldn't read file: $!";
        print "Content-type: image/svg+xml\nExpires: 0\n\n";
        print $buffer;
    } else {
        print $cgi->header(-expires=>'now',refresh=>'300')),"<img border=0 src=\"",
            $cgi->self_url(),$sep,"mode=svg\"/>\n",$cgi->end_html;
    }
} else {
    my $file="$dir/$param::file".'.fig.used';
    my $fh=new IO::File("$cat $file|") || die;
    my @data=<$fh>;
    my $fig=new CIBH::Fig(fig=>[@data]);

    if($param::mode eq 'png') {
        $fig->BuildImage;
        print "Content-type: image/png\nExpires: 0\n\n",$fig->png;
    } else {
        $fig->BuildMap;
        warn $cgi->self_url();
        print
            $cgi->header(-expires=>'now',refresh=>'300'),
            $cgi->start_html(-title=>'Barn Mapping',
                       -author=>$author,
                       -BGCOLOR=>'ffffff'),
            "<img border=0 src=\"",
            $cgi->self_url(),$sep,
            "mode=png\" usemap=\"\#mymap\"/>\n",
            "<map name=mymap>\n",
            $fig->csImageMap,
            "</map>\n",
            $cgi->end_html;
    }
}
