#!/bin/sh

PATH=$PATH:$HOME/cibh/scripts

DATA=$(perl -MCIBH::Config -E '$CIBH::Config::default_options->{data_path} =~ s/\/snmp//; say $CIBH::Config::default_options->{data_path}')

for NETWORK in $*
do
  export NETWORK
  snmp-poll-all $DATA/routers
  usage2fig $DATA/figs/*.fig $DATA/figs/*.gv
done

