#!/bin/sh

PATH=$PATH:$HOME/cibh/scripts

NET=$*
if [ -z "$NET" ]; then
    NET=$(perl -MCIBH::Config -E 'say CIBH::Config::load_cibhrc()->{network}')
fi

for NETWORK in $NET
do
  export NETWORK
  DATA=$(perl -MCIBH::Config -E 'CIBH::Config::load_cibhrc()->{base_path}')
  snmp-poll-all $DATA/routers
  usage2fig $DATA/figs/*.fig $DATA/figs/*.gv
done

