#!/bin/sh

if [ "x$MAX_PROCS" = "x" ]; then
    MAX_PROCS=10
fi

PATH=$PATH:$HOME/cibh/scripts
# We might want to split the list of routers into groups of x size then pass
# those groups to snmp-poll.  That way we don't have to fork for each one, but
# can instead do, for example, 10 routers per process, 10 processes at a time,
# for 100 routers per second, or thereabouts.
#
# parallel supports this, so par is now (probably) the worst of the three options
# despite having the best terminal support.
if which parallel >/dev/null; then
    cat $* | parallel --no-notice -X -j $MAX_PROCS 'snmp-poll {}'
elif which par >/dev/null; then
    par -n $MAX_PROCS -q -c "snmp-poll {}" $*
else
    snmp-poll `cat $*`
fi

