#!/bin/sh

if [ "x$MAX_PROCS" = "x" ]; then
    MAX_PROCS=10
fi

PATH=$PATH:$HOME/cibh/scripts
# We might want to split the list of routers into groups of x size then pass
# those groups to snmp-poll.  That way we don't have to fork for each one, but
# can instead do, for example, 10 routers per process, 10 processes at a time,
# for 100 routers per second, or thereabouts.
if which par >/dev/null; then
    par -n $MAX_PROCS -q -c "snmp-poll {}" $*
elif which parallel >/dev/null; then
    parallel --no-notice -j $MAX_PROCS 'snmp-poll {}' < $*
else
    for rtr in `cat $*`
    do
      snmp-poll $rtr
    done
fi

